using Courtyard.Water;
using System.Diagnostics;

int failures = 0, count = 0;
void Check(string name, Action action) { count++; try { action(); Console.WriteLine("PASS " + name); } catch (Exception e) { failures++; Console.WriteLine("FAIL " + name + ": " + e.Message); } }
void Require(bool condition, string detail) { if (!condition) throw new Exception(detail); }
void Near(double actual, double expected, double tolerance, string detail) => Require(Math.Abs(actual-expected)<=tolerance, $"{detail}: {actual} expected {expected}");
WaterGrid Pool(int n=32) => new WaterGrid(n,n,0.25f,new float[n*n]);
Check("Closed pool conserves volume over 60 seconds", () => { var g=Pool(); g.Fill(2); double v=g.Volume; Near(v,128,.001,"initial volume"); for(int i=0;i<3000;i++)g.Step(.02f); Near(g.Volume,v,.002,"volume"); });
Check("Initial fill respects solid steps", () => { var b=new float[16]; b[0]=3; var g=new WaterGrid(4,4,1,b); g.Fill(2); Near(g.Depth(0),0,0,"dry step"); Near(g.Volume,30,.0001,"solid excluded"); });
Check("Disturbance spreads to other cells and conserves volume", () => {var g=Pool();g.Fill(2);double v=g.Volume;Near(g.Depth(12+14*32),2,.0001,"initial surface");g.Displace(12,12,.018f); for(int i=0;i<40;i++)g.Step(.02f); Require(Math.Abs(g.Depth(12+14*32)-2)>.0001,"no propagated wave");Near(g.Volume,v,.002,"wave volume");});
Check("Open drain removes local water and generates a surface gradient", () => {var g=Pool();g.Fill(2);g.SetDrain(4,4,.5f,1.5f);double v=g.Volume;for(int i=0;i<50;i++)g.Step(.02f);Require(g.Volume<v-1,"no discharge");Require(g.Depth(4+4*32)<g.Depth(26+26*32)-.005,"no local depression");Require(g.FlowSpeed(4,6)>.005,"no flow");Near(g.Volume+g.Discharged,v,.003,"outflow ledger");});
Check("Closed valve has no discharge",()=>{var g=Pool();g.Fill(1);g.SetDrain(4,4,.5f,0);for(int i=0;i<100;i++)g.Step(.02f);Near(g.Discharged,0,0,"closed drain");});
Check("Drain empties pool without negative depths",()=>{var g=Pool(16);g.Fill(1);g.SetDrain(8,8,.6f,3);for(int i=0;i<12000;i++)g.Step(.02f);Require(g.Volume<.025,"residual "+g.Volume);for(int i=0;i<256;i++)Require(g.Depth(i)>=0&&!float.IsNaN(g.Depth(i)),"negative/nonfinite");Near(g.Volume+g.Discharged,16,.008,"mass ledger");});
Check("Water cannot cross a high solid partition",()=>{var b=new float[16*16];for(int z=0;z<16;z++)b[z*16+8]=4;var g=new WaterGrid(16,16,.25f,b);g.Fill(1);g.SetDrain(3,8,.5f,2);for(int i=0;i<3000;i++)g.Step(.02f);Near(g.Depth(12+8*16),1,.0001,"water crossed wall");});
Check("Frame subdivision is deterministic",()=>{var a=Pool(16);var b=Pool(16);a.Fill(2);b.Fill(2);a.SetDrain(8,8,.5f,2);b.SetDrain(8,8,.5f,2);for(int i=0;i<100;i++){a.Step(.02f);b.Step(.01f);b.Step(.01f);}Near(a.Volume,b.Volume,.03,"step convergence");});
Check("Reset restores state and clears drainage",()=>{var g=Pool();g.Fill(2);g.SetDrain(4,4,.5f,2);for(int i=0;i<100;i++)g.Step(.02f);g.Fill(2);Near(g.Volume,128,.001,"reset volume");Near(g.Discharged,0,0,"reset meter");});
Check("Drain receiver needs continuous illumination then latches",()=>{var g=new DrainGate(1.5f);g.Tick(true,1);Require(!g.IsOpen,"early unlock");g.Tick(false,.2f);g.Tick(true,1);Require(!g.IsOpen,"charge not reset");g.Tick(true,.6f);Require(g.IsOpen,"not unlocked");g.Tick(false,20);Require(g.IsOpen,"drain closed after light moved");g.Reset();Require(!g.IsOpen,"reset failed");});
Check("Buoyancy fraction brackets waterline",()=>{Near(HydroMath.SubmergedFraction(2,1,0),0,0,"above water");Near(HydroMath.SubmergedFraction(0,1,0),.5,.0001,"half");Near(HydroMath.SubmergedFraction(-2,1,0),1,0,"under water");});
Check("Refraction obeys Snell law and level does not change angle",()=>{double a=HydroMath.RefractedAngle(Math.PI/4,1,1.333);Near(Math.Sin(a)*1.333,Math.Sin(Math.PI/4),.000001,"Snell");Require(a<Math.PI/4,"did not bend toward normal");});
Check("Total internal reflection is reported",()=>Require(double.IsNaN(HydroMath.RefractedAngle(1.3,1.333,1)),"missing TIR"));
Check("Invalid domain is rejected",()=>{bool caught=false;try{new WaterGrid(1,4,0,new float[4]);}catch(ArgumentException){caught=true;}Require(caught,"invalid grid accepted");});
Check("Nonfinite disturbances cannot poison the solver",()=>{var g=Pool();g.Fill(2);bool caught=false;try{g.Displace(8,8,float.NaN);}catch(ArgumentException){caught=true;}Require(caught,"NaN disturbance accepted");Near(g.Volume,128,.001,"state preserved");});
Check("Nonfinite drain radius is rejected",()=>{var g=Pool();bool caught=false;try{g.SetDrain(8,8,float.PositiveInfinity,1);}catch(ArgumentException){caught=true;}Require(caught,"infinite radius accepted");});
Check("Disturbed water query matches reconstructed mesh triangles",()=>{var g=Pool();g.Fill(2);g.Displace(12,12,.1f);g.Step(1f/30);float Corner(int x,int z)=>(g.Surface(x-1+(z-1)*32)+g.Surface(x+(z-1)*32)+g.Surface(x-1+z*32)+g.Surface(x+z*32))*.25f;float meshCenter=(Corner(13,12)+Corner(12,13))*.5f;Near(g.SampleSurface(12.5f,12.5f),meshCenter,.000001,"render and physics surface");});
Check("Graded courtyard exposes the pool floor within 200 seconds",()=>{var bed=new float[48*64];for(int z=0;z<64;z++)for(int x=0;x<48;x++){float dx=(x+.5f)*.25f-6-2.2f,dz=(z+.5f)*.25f-8-2.8f;bed[x+z*48]=-4.5f+(float)Math.Sqrt(dx*dx+dz*dz)*.02f;}var g=new WaterGrid(48,64,.25f,bed);g.Fill(-.6f);double initial=g.Volume;g.SetDrain(32,43,.9f,3.2f);for(int i=0;i<6000;i++)g.Step(1f/30);Require(g.Volume/initial<.005,"remaining fraction "+g.Volume/initial);Near(g.Volume+g.Discharged,initial,.0001,"large pool conservation");});
Check("Four-times drainage exposes the courtyard floor within 50 real seconds",()=>{
    var bed=new float[48*64];for(int z=0;z<64;z++)for(int x=0;x<48;x++){float dx=(x+.5f)*.25f-8.2f,dz=(z+.5f)*.25f-10.8f;bed[x+z*48]=-4.5f+(float)Math.Sqrt(dx*dx+dz*dz)*.02f;}
    var g=new WaterGrid(48,64,.25f,bed);g.Fill(-.6f);g.DrainSpeedMultiplier=4;g.SetDrain(32,43,.9f,3.2f);double initial=g.Volume;
    for(int i=0;i<1500;i++)g.Step(1f/30);
    Require(g.Volume/initial<.005,"Remaining fraction "+g.Volume/initial);
    Near(g.Volume+g.Discharged,initial,.0001,"Accelerated conservation");
    for(int i=0;i<48*64;i++)Require(g.Depth(i)>=0&&float.IsFinite(g.Depth(i)),"Invalid accelerated water depth");
});
Check("Drain speed does not accelerate a closed pool",()=>{var a=Pool(16);var b=Pool(16);a.Fill(2);b.Fill(2);b.DrainSpeedMultiplier=8;a.Displace(8,8,.04f);b.Displace(8,8,.04f);for(int n=0;n<100;n++){a.Step(.02f);b.Step(.02f);}for(int n=0;n<256;n++)Near(a.Depth(n),b.Depth(n),0,"Closed pool speed");});
Check("Outflow meter reports volume per real second at eight-times speed",()=>{var g=Pool();g.Fill(2);g.DrainSpeedMultiplier=8;g.SetDrain(4,4,.5f,1);double before=g.Discharged;g.Step(.25f);Near(g.LastDischargeRate,(g.Discharged-before)/.25,.00001,"Rate units");Near(g.Volume+g.Discharged,128,.00001,"Maximum speed conservation");});
Check("Unsafe drain speed is rejected",()=>{var g=Pool();foreach(float value in new[]{float.NaN,float.PositiveInfinity,0,9}){bool caught=false;try{g.DrainSpeedMultiplier=value;}catch(ArgumentOutOfRangeException){caught=true;}Require(caught,"Unsafe speed accepted");}Near(g.DrainSpeedMultiplier,1,0,"Rejected values preserved state");});
Check("Sea seam rejects capsule contact on every edge and corner",()=>{var b=new CoastalTemple.SeaBounds(-144,144,-88,256);Require(b.ContainsDisc(0,100,.35f),"safe inland point");foreach(var p in new[]{(-143.65f,0f),(143.65f,0f),(0f,-87.65f),(0f,255.65f),(144f,256f)})Require(!b.ContainsDisc(p.Item1,p.Item2,.35f),"seam contact escaped");Require(b.ContainsDisc(143,255,.35f),"safe water killed");});
Check("Sea seam catches a fast crossing and invalid coordinates",()=>{var b=new CoastalTemple.SeaBounds(-144,144,-88,256);foreach(var p in new[]{(1000f,10f),(-1000f,10f),(0f,-1000f),(0f,1000f),(float.NaN,0f)})Require(!b.ContainsDisc(p.Item1,p.Item2,.35f),"outside point accepted");});
Check("Coastal wave crosses wet cells without flooding an island",()=>{int n=40;var bed=new float[n*n];for(int z=0;z<n;z++)for(int x=0;x<n;x++)bed[x+z*n]=(x>12&&x<28&&z>12&&z<28)?8:-4;var g=new WaterGrid(n,n,2,bed);g.Fill(-1.7f);double volume=g.Volume;g.Displace(5,5,1.2f);for(int i=0;i<80;i++)g.Step(.05f);Require(Math.Abs(g.Surface(7+5*n)+1.7f)>.0001,"nearshore wave did not propagate");Near(g.Depth(20+20*n),0,0,"island flooded");Near(g.Volume,volume,.001,"coastal wave conservation");});
var perf=Pool(64);perf.Fill(4);perf.SetDrain(32,32,1,5);var watch=Stopwatch.StartNew();for(int i=0;i<500;i++)perf.Step(.02f);watch.Stop();Console.WriteLine($"PERF 64x64 grid: {watch.Elapsed.TotalMilliseconds/500:F3} ms / 20ms step (CPU numerical core)");
Check("Ocean dry corners cannot stretch a water triangle up a cliff",()=>{var bed=new float[16];for(int z=0;z<4;z++)for(int x=0;x<4;x++)bed[x+z*4]=x>=2?40:-9;var g=new WaterGrid(4,4,4,bed);g.DrySurfaceCeiling=-1.7f;g.Fill(-1.7f);Near(g.VertexSurface(3,2),-1.7,.00001,"dry corner ceiling");Near(g.SampleSurface(2.7f,1.3f),-1.7,.00001,"physics follows bounded mesh");});
Check("Ocean waves are bounded, animated and reversible by zero amplitude",()=>{float max=0;for(int i=0;i<1000;i++){float h=OceanWaveMath.Height(i*.37f,i*.12f,7,i*.09f,1,1,1,1);max=Math.Max(max,Math.Abs(h));Require(float.IsFinite(h)&&Math.Abs(h)<=.626f,"unbounded wave");}Require(max>.35f,"no visible wave");Near(OceanWaveMath.Height(12,30,5,4,0,1,1,1),0,0,"zero amplitude");Require(Math.Abs(OceanWaveMath.Height(12,30,5,4,1,1,1,1)-OceanWaveMath.Height(12,30,5,5,1,1,1,1))>.01,"frozen waves");});
Check("Ocean geometry joins the flat far sea without a crack",()=>{Near(OceanWaveMath.EdgeEnvelope(144,20,-144,-88,144,256,12),0,0,"right seam");Near(OceanWaveMath.EdgeEnvelope(0,-88,-144,-88,144,256,12),0,0,"south seam");Near(OceanWaveMath.EdgeEnvelope(200,20,-144,-88,144,256,12),0,0,"far sea");Near(OceanWaveMath.Height(144,20,7,9,1,1,1,0),0,0,"edge displacement");Near(OceanWaveMath.Height(4,5,0,9,1,1,1,1),0,0,"dry shore");});
Check("Solver disturbances also join the static sea at its exact level",()=>{var bed=new float[72*86];Array.Fill(bed,-9);var g=new WaterGrid(72,86,4,bed){BoundarySurfaceFadeMetres=12,BoundarySurfaceLevel=-1.7f};g.Fill(-1.7f);double v=g.Volume;g.Displace(70,40,.9f);for(int n=0;n<20;n++){Near(g.VertexSurface(72,40),-1.7,.000001,"right seam");Near(g.SampleSurface(72,40.5f),-1.7,.000001,"query at seam");g.Step(.05f);}Near(g.Volume,v,.001,"edge rendering must not destroy solver volume");});
Console.WriteLine($"RESULT {count-failures}/{count} passed"); Environment.ExitCode=failures==0?0:1;
